### ISSUE TITLE
gee-atmcorr-S2-6SE display median() image?

### ISSUE THREAD

**Issue by thanhgis** [samsammurphy/gee-atmcorr-S2-6SE#1]
Hi Sam, 

Is there any way to make it compatible between your gee-atmcorr-S2-6SE and GEE Python API? I tried to translate from Python3 to Python27 to apply into my study (changes detection using Landsat-8 and Sentinel-2), but it seems I am not capable. 

Thank you!

**Comment by thanhgis** [comment]
Dear Mr. Sam Murphy, 

I am trying to learn your code, but I could not display the median() or mosaic() image in your notebook example file. 

When I try: 
test = ic_atmospherically_corrected.median()
dis_test = Image(url=test.select(['B4','B3','B2']).getThumbUrl({
                'region':region,
                'min':0,
                'max':0.25,
                'gamma':1.5
                })) 
display(dis_test)

The screen just shows nothing, neither image nor errors.

Could you please teach me how to display median() or mosaic() image?

Thank you so much.

**Comment by samsammurphy** [comment]
HI Than,

I just gave that a go, running into the same issue, will look into how to try and resolve this.

**Comment by thanhgis** [comment]
Dear Sam, 

If you don't mind, pls accept this work-around. Both mosaic() and median() work.

https://drive.google.com/open?id=0B18gqYnNEgSpUERidUZ5YmVuZkE

Thanks

**Comment by samsammurphy** [comment]
Thank you!

I am going to be at a conference over the next week, so might take me about that long to integrate

**Comment by samsammurphy** [comment]
sorry that I didnt get around to doing this.. I am going to be archiving this repository. thank you for your input!!
